### ISSUE TITLE
安装qff后出现问题

### ISSUE THREAD

**Issue by YP-Ye** [haijiangxu/qff#3]
命令行输入`qff --version`提示
`
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\qff.exe\__main__.py", line 7, in <module>
  File "C:\Anaconda3\lib\site-packages\qff\__main__.py", line 74, in main
    'run': RunCommand(sub_parser),
  File "C:\Anaconda3\lib\site-packages\qff\frame\cli.py", line 78, in __init__
    super().__init__('run', sub_parser)
  File "C:\Anaconda3\lib\site-packages\qff\frame\cli.py", line 58, in __init__
    self.add_options()
  File "C:\Anaconda3\lib\site-packages\qff\frame\cli.py", line 96, in add_options
    self.parser.add_argument("-l", "--log-level", hoices=['verbose', 'info', 'warning', 'error'], default='info',
  File "C:\Anaconda3\lib\argparse.py", line 1368, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'hoices'
`

**Comment by haijiangxu** [comment]
已修复，运行pip install -U qff
